### PR TITLE
OPENTOK-44181: Add sample app for XCFramework

### PR DESCRIPTION
**Pull request by jvalli**
#### What is this PR doing?
Add sample app for XCFramework

#### What are the relevant tickets?

[OPENTOK-44181](https://jira.vonage.com/browse/OPENTOK-44181)

This PR is depends of the approval of a new cocoapod repository: https://github.com/opentok/native-sdk-src/pull/3409

### CODE REVIEW

**Comment by IGitGotIt** [comment]
Functionality-wise this app is same as Basic App. Why create a new sample app when we can fold the xcframework instructions into a separate section of  the Basic app readme.

**Comment by jvalli** [comment]
> Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.

That was the request on the ticket description. I think they want to share that example to some clients.

**Comment by IGitGotIt** [comment]
> > Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.
> 
> That was the request on the ticket description. I think they want to share that example to some clients.





> > Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.
> 
> That was the request on the ticket description. I think they want to share that example to some clients.


How do I use it with screen sharing app? or integrate with custom audio ? or frame meta data app?

You will need generalized readme instructions in all of the above apps, at some point.

**Comment by jvalli** [comment]
> > > Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.
> > 
> > 
> > That was the request on the ticket description. I think they want to share that example to some clients.
> 
> > > Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.
> > 
> > 
> > That was the request on the ticket description. I think they want to share that example to some clients.
> 
> How do I use it with screen sharing app? or integrate with custom audio ? or frame meta data app?
> 
> You will need generalized readme instructions in all of the above apps, at some point.

I am not sure to get your point @IGitGotIt. Why do we need to explain other features of the SDK with more demo apps?
We just want to let people know about how to get and import the SDK into a simple app based on the .xcframework format.

**Comment by v-kpheng** [comment]
> > > Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.
> > 
> > 
> > That was the request on the ticket description. I think they want to share that example to some clients.
> 
> > > Functionality-wise this app is same as Basic App. we can fold the xcframework instructions into a separate section of the Basic app readme.
> > 
> > 
> > That was the request on the ticket description. I think they want to share that example to some clients.
> 
> How do I use it with screen sharing app? or integrate with custom audio ? or frame meta data app?
> 
> You will need generalized readme instructions in all of the above apps, at some point.

Thanks, @IGitGotIt .

This addition to our repo serves the following purposes:
* Let's us do end-to-end testing of XCFramework.
* Provides our users w/ an example of how to incorporate XCFramework artifacts into their workflows.

As such, additional samples aren't required...at least for now.  Let's cross that bridge when we get there, please.

**Comment by IGitGotIt** [comment]
@v-kpheng @jvalli All I am saying is have a readme  instructions on how to install xcframeworks in your app. Just point to this in the readme of various samples and you are done. You don't need an app or many apps  to do that. Thanks.

**Comment by v-kpheng** [comment]
> @v-kpheng @jvalli Sorry if I was not clear before. All I am saying is to have instructions on how to install xcframeworks You don't need an app to do that.
> 
> For example something like: https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/
> 
> Thanks

Thanks, @IGitGotIt.  Typically, that would be sufficient.  However, one goal is to use this new sample repo for end-to-end testing, with as little change required as possible.

**Comment by IGitGotIt** [comment]
> > @v-kpheng @jvalli Sorry if I was not clear before. All I am saying is to have instructions on how to install xcframeworks You don't need an app to do that.
> > For example something like: https://www.simpleswiftguide.com/how-to-add-xcframework-to-xcode-project/
> > Thanks
> 
> Thanks, @IGitGotIt. Typically, that would be sufficient. However, one goal is to use this new sample repo for end-to-end testing, with as little change required as possible.

Normally we don't put helper test apps in a public facing repo. We can put it elsewhere in a private repo. 

The steps/instructions on how to incorporate a xcframework , is an important aspect. Without it partners would be looking elsewhere on how to do it.  A ready made app with xcframework will not give a clue as to how it was  `all ` put together or how to duplicate it in their app. 

Please feel free to ok this PR if you think otherwise. 

Thanks

**Review by v-kpheng — APPROVED** [review]
LGTM! 🚀 💪

**Pull request merged**
