### PR TITLE
MODIFY Set EGL context to nil to prevent crash when deallocating.

### PR DESCRIPTION
**Pull request by wobbals**
Bug introduced in iOS 9?
From @SteveMcFarlin

### CODE REVIEW

**Comment by wobbals** [comment]
merge this please

**Comment by SteveMcFarlin** [comment]
I am not sure if it is a bug, or we were just getting lucky. I did a search when this came up, and someone said they fixed the issue by using that line of code in the dealloc method. That post was on iOS 7.

**Comment by wobbals** [comment]
Do you think we need to do anything more here?

**Comment by SteveMcFarlin** [comment]
At this point I am not sure. I assume the guy is still having crash issues (glanced at some of the support emails). Has he sent in any new stack traces sense the fix was given to him?

**Pull request closed without merging**
