### PR TITLE
OPENTOK-23360 Add a spinner view while stream is being connected

### PR DESCRIPTION
**Pull request by robjperez**

### CODE REVIEW

**Comment by wobbals** [comment]
You sure we want something like this for hello-world? The goal of that particular app is for minimalism.

**Comment by cpbrew** [comment]
Agree with @wobbals, hello-world is meant to be a bare-minimum code demo, not a UX guide.

**Comment by JayTokBox** [comment]
+ 5 million

**Comment by JayTokBox** [comment]
agree with @wobbals 100%

**Pull request closed without merging**
