### PR TITLE
MODIFY debounce audio category when performing a reset

### PR DESCRIPTION
**Pull request by wobbals**
Resetting the audio pipeline for a category change included a routine to set the audio session category back to whatever previous value it held, which triggers a route change, which triggers a reset, which triggers a category change...

OPENTOK-27597

### CODE REVIEW

**Comment by wobbals** [comment]
Shout out to @keepingitneil who already identified and fixed this before we even noticed :smile:

**Comment by keepingitneil** [comment]
cheers!

**Comment by wobbals** [comment]
@bsrao customer reports indicate this patch fixes the issue. Can we merge this?

**Comment by bsrao** [comment]
@wobbals Yes, Thanks

**Comment by bsrao** [comment]
merge this please

**Pull request closed without merging**
