### PR TITLE
restructure to populate Podfile to each folder

### PR DESCRIPTION
**Pull request by Lucashuang0802**

### CODE REVIEW

**Comment by robjperez** [comment]
It will be nice if the version of the OpenTok pod is just in a single file, do you think we could have something which is not very confusing?

**Comment by Lucashuang0802** [comment]
@robjperez definitely agree on the point but it seems to make us convenient only. Well, it's not that convenient if you want to do `pod deintegrate`, we will have to go into each folder to perform that. As well, it will be confusing for developers who are not familiar to have multiple targets and multiple projects in the same workspace. Based on the comment from @JayTokBox, it's also a rare case for developers to switch projects frequently.

**Comment by robjperez** [comment]
Having N or just one project is something we can discuss, but with the previous comment I was referring just to the fact of having the version of OpenTok SDK in a single place.

We could have N Podfiles with N projects, but in each Podfile something like this
```
include OpenTokVersion.rb //-> $OpenTokSDKVersion = '=2.11.1'

pod 'OpenTok', $OpenTokSDKVersion
```

I'm not sure if this can be done using Podfiles but it will save of typing 2.11.1 N times (and probably forgetting some of them)

**Comment by Lucashuang0802** [comment]
@robjperez looks like I completed misunderstood. Yes, let me try it out. It should be working. 😄 👍

**Pull request merged**
