### PR TITLE
OPENTOK-30219 Audio driver revamp

### PR DESCRIPTION
**Pull request by wobbals**

### CODE REVIEW

**Comment by bsrao** [comment]
@wobbals  LGTM. Thanks.
One question though, are those Xcode pod settings changes are necessary ?

**Comment by wobbals** [comment]
Yep - new cocoapods breaks linking phase with our old project configs. LMK if you prefer this in a separate PR, sorry about the combination.

**Comment by bsrao** [comment]
Thats perfectly fine, I was just curious.

**Comment by wobbals** [comment]
merge this por favor

**Pull request closed without merging**
